"""Generated by ShowNet from a captured session.

Read GAPS.md before relying on this. Anything ShowNet could not confirm
from the capture is marked there and at the line that depends on it.
"""

from __future__ import annotations

from typing import Any

from curl_cffi import requests

from .fingerprint import CONTRACT, verify_fingerprint


def _pointer(payload: Any, pointer: str) -> Any:
    """Resolve a JSON pointer, returning None rather than raising."""
    current = payload
    for part in pointer.split("/"):
        if part == "":
            continue
        if isinstance(current, list):
            try:
                current = current[int(part)]
            except (ValueError, IndexError):
                return None
        elif isinstance(current, dict):
            if part not in current:
                return None
            current = current[part]
        else:
            return None
    return current
